name: nhctl

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build-nhctl-windows-linux:
    name: Build nhctl
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Build
        run: |
          export GITHUB_ACTION=true
          make nhctl-linux
          make nhctl-windows
          make nhctl-linux-arm64

      - name: Push to Coding Artifacts
        if: ${{ github.repository == 'nocalhost/nocalhost' }}
        env:
          WINDOWS_BINARY: 'nhctl-windows-amd64.exe'
          LINUX_BINARY: 'nhctl-linux-amd64'
          LINUX_ARM64_BINARY: 'nhctl-linux-arm64'
        run: |
          cd build
          curl -T ${WINDOWS_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_BINARY}?version=${GITHUB_SHA}" --retry 5
          curl -T ${LINUX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_BINARY}?version=${GITHUB_SHA}" --retry 5
          curl -T ${LINUX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_ARM64_BINARY}?version=${GITHUB_SHA}" --retry 5

      - name: Push to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' }}
        env:
          WINDOWS_BINARY: 'nhctl-windows-amd64.exe'
          LINUX_BINARY: 'nhctl-linux-amd64'
          LINUX_ARM64_BINARY: 'nhctl-linux-arm64'
        run: |
          cd build
          curl -T ${WINDOWS_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_BINARY}?version=main" --retry 5
          curl -T ${LINUX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_BINARY}?version=main" --retry 5
          curl -T ${LINUX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_ARM64_BINARY}?version=main" --retry 5

      - name: Push to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'nocalhost/nocalhost' }}
        env:
          WINDOWS_BINARY: 'nhctl-windows-amd64.exe'
          LINUX_BINARY: 'nhctl-linux-amd64'
          LINUX_ARM64_BINARY: 'nhctl-linux-arm64'
        run: |
          cd build
          curl -T ${WINDOWS_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_BINARY}?version=dev" --retry 5
          curl -T ${LINUX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_BINARY}?version=dev" --retry 5
          curl -T ${LINUX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_ARM64_BINARY}?version=dev" --retry 5

  build-nhctl-macos:
    name: Build nhctl
    runs-on: macos-11
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Build
        run: |
          export GITHUB_ACTION=true
          make nhctl-osx
          make nhctl-osx-arm64

      - name: Push to Coding Artifacts
        if: ${{ github.repository == 'nocalhost/nocalhost' }}
        env:
          OSX_BINARY: 'nhctl-darwin-amd64'
          OSX_ARM64_BINARY: 'nhctl-darwin-arm64'
        run: |
          cd build
          curl -T ${OSX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${OSX_BINARY}?version=${GITHUB_SHA}" --retry 5
          curl -T ${OSX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${OSX_ARM64_BINARY}?version=${GITHUB_SHA}" --retry 5

      - name: Push to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' }}
        env:
          OSX_BINARY: 'nhctl-darwin-amd64'
          OSX_ARM64_BINARY: 'nhctl-darwin-arm64'
        run: |
          cd build
          curl -T ${OSX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${OSX_BINARY}?version=main" --retry 5
          curl -T ${OSX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${OSX_ARM64_BINARY}?version=main" --retry 5

      - name: Push to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'nocalhost/nocalhost' }}
        env:
          OSX_BINARY: 'nhctl-darwin-amd64'
          OSX_ARM64_BINARY: 'nhctl-darwin-arm64'
        run: |
          cd build
          curl -T ${OSX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${OSX_BINARY}?version=dev" --retry 5
          curl -T ${OSX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://nocalhost-generic.pkg.coding.net/nocalhost/nhctl/${OSX_ARM64_BINARY}?version=dev" --retry 5
